---
- name: install the openjdk-7 package
  apt:
    pkg=openjdk-7-jdk
    state=latest
  register: openjdk_7_installed
  tags:
    - java
    - packages

- name: change openjdk to be version 7
  command: update-java-alternatives -s java-1.7.0-openjdk-amd64
  when: openjdk_7_installed|changed
  tags:
    - java
    - packages