---
- name: Ensure openjdk-7 is installed
  apt:
    pkg=openjdk-7-jdk
    state=latest
  register: openjdk_7_installed
  tags:
    - java
    - packages

- name: Ensure java is using change openjdk-7
  alternatives: name=java path=/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
  when: openjdk_7_installed|changed
  tags:
    - java
    - packages